framework:
#    translator: { fallbacks: [ "fr" ] }
#    default_locale: '%locale%'
#    translator:
#        default_path: '%kernel.project_dir%/translations'
#        fallbacks:
#            - '%locale%'
